"""add authentication fields to users

Revision ID: a284dd73e877
Revises: 9959abeab4c6
Create Date: 2026-09-23 21:35:50.386333
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'a284dd73e877'
down_revision: Union[str, Sequence[str], None] = '9959abeab4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), server_default='!', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
